runtime: python39
service: default
handlers:
  # Initial route that will serve up index.html, main entry point to your app
  - url: /
    secure: always
    static_files: dist/front-auth/browser/index.html
    upload: dist/front-auth/browser/.*

  # Routing for typedoc, assets and favicon.ico to serve directly
  - url: /((?:assets|docs)/.*|favicon\.ico)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/front-auth/browser/\1
    upload: dist/front-auth/browser/.*

  # Routing for any js files
  - url: /(.*\.js)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/front-auth/browser/\1
    upload: dist/front-auth/browser/.*\.js

  # Routing for any css files
  - url: /(.*\.css)
    secure: always
    redirect_http_response_code: 301
    static_files: dist/front-auth/browser/\1
    mime_type: text/css
    upload: dist/front-auth/browser/.*\.css

  # Routing for anything (wild card) after
  - url: /.*
    secure: always
    static_files: dist/front-auth/browser/index.html
    upload: dist/front-auth/browser/.*
